package com.ucsdregistration.web_backend.Entity;

import jakarta.persistence.*;
import lombok.*;
import java.util.*;
import java.time.LocalDateTime;

@Data
@Entity
@Table(name="course_professor_comments")
public class Comment {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // generated by database
    @Column(name="comment_id")
    private Long commentId;

    @Column(name="course_offering_id", nullable=false)
    private String courseOfferingId;
    
    @Column(name="prof_id", nullable=false)
    private String profId;
    
    @Column(name="comment", columnDefinition = "TEXT")
    private String comment;
   
    @Column(name="created_at", insertable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name="updated_at", insertable = false, updatable = false)
    private LocalDateTime updatedAt;
    
    @Column(name="like_ct")
    private Integer likeCt;

    @Column(name="dislike_ct")
    private Integer dislikeCt;

    public Comment(){}

    public Comment(String courseOfferingId, String profId, String commentContent){
        this.courseOfferingId = courseOfferingId;
        this.profId = profId;
        this.comment = commentContent;
    }
}   
