spring.application.name=web-backend
server.port=8080

# 设置默认的日志级别
logging.level.root=WARN
# 也可以为特定的包设置级别，例如让Spring框架本身保持安静，但是让我们自己的项目打印DEBUG信息
# logging.level.org.springframework=WARN
# logging.level.com.ucsdregistration=DEBUG # 假设这是你项目的根包名

# MySQL DataSource
spring.datasource.url=${UCSD_REG_DB_URL} 
spring.datasource.username=${UCSD_REG_DB_USER}
spring.datasource.password=${UCSD_REG_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

